logging:
  level:
    root: debug

spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true